[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wzec_bridge = "HefTNtytDcQgSQmBpPuwjGipbVcJTMRHnppU9poWRXhD"

[programs.testnet]
wzec_bridge = "HefTNtytDcQgSQmBpPuwjGipbVcJTMRHnppU9poWRXhD"

[programs.devnet]
wzec_bridge = "HefTNtytDcQgSQmBpPuwjGipbVcJTMRHnppU9poWRXhD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
